// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpnX0eXWD-XNdVOEQw_82eWSRkAbjxtm8',
    appId: '1:763365250072:web:7ea7fdf4b922c07c36df6d',
    messagingSenderId: '763365250072',
    projectId: 'vayu-sutra',
    authDomain: 'vayu-sutra.firebaseapp.com',
    storageBucket: 'vayu-sutra.firebasestorage.app',
    measurementId: 'G-JBSJV2553F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXzHVHBeaEgOa5GXZ53d8ohWov9OOtY8',
    appId: '1:763365250072:android:e73dd9ea4e99ce6b36df6d',
    messagingSenderId: '763365250072',
    projectId: 'vayu-sutra',
    storageBucket: 'vayu-sutra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBBGwiqd-m5TuedA9kpnKJRfn5rc8UyzI',
    appId: '1:763365250072:ios:035bb3fe161d34ea36df6d',
    messagingSenderId: '763365250072',
    projectId: 'vayu-sutra',
    storageBucket: 'vayu-sutra.firebasestorage.app',
    iosBundleId: 'com.pollutionmonitor.pollutionMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBBGwiqd-m5TuedA9kpnKJRfn5rc8UyzI',
    appId: '1:763365250072:ios:035bb3fe161d34ea36df6d',
    messagingSenderId: '763365250072',
    projectId: 'vayu-sutra',
    storageBucket: 'vayu-sutra.firebasestorage.app',
    iosBundleId: 'com.pollutionmonitor.pollutionMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpnX0eXWD-XNdVOEQw_82eWSRkAbjxtm8',
    appId: '1:763365250072:web:8f0ea6a7f856f60a36df6d',
    messagingSenderId: '763365250072',
    projectId: 'vayu-sutra',
    authDomain: 'vayu-sutra.firebaseapp.com',
    storageBucket: 'vayu-sutra.firebasestorage.app',
    measurementId: 'G-NR6SWHR2N0',
  );
}
